name: CI DevOps Lab

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build artefact
        run: |
          mkdir -p build
          echo "Build gerado em $(date)" > build/info.txt
          ls -l build

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: devops-build
          path: build/
