name: CI/CD DevOps Lab

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build artefact
        run: |
          mkdir -p build
          echo "Build gerado em $(date)" > build/info.txt

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: devops-build
          path: build/

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev   # üëà DEV n√£o precisa aprova√ß√£o

    steps:
      - name: Download artefact
        uses: actions/download-artifact@v4
        with:
          name: devops-build
          path: build/

      - name: Deploy to DEV
        run: |
          echo "Deploy autom√°tico em DEV"
          cat build/info.txt
          echo "Deploy DEV conclu√≠do"

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: production   # üëà PROD exige aprova√ß√£o

    steps:
      - name: Download artefact
        uses: actions/download-artifact@v4
        with:
          name: devops-build
          path: build/

      - name: Deploy to PROD
        run: |
          echo "Deploy em PRODU√á√ÉO (com aprova√ß√£o)"
          cat build/info.txt
          echo "Deploy PROD conclu√≠do"
